# WINDOW SETTING
WIDTH_MAIN_SCREEN = 1200
HEIGHT_MAIN_SCREEN = 800

WIDTH_GAME_SCREEN = 400
HEIGHT_GAME_SCREEN = 600

WIDTH_GRAPH_SCREEN = 800
HEIGHT_GRAPH_SCREEN = 600

WIDTH_STATS_SCREEN = 400
HEIGHT_STATS_SCREEN = 200

WIDTH_CONTROL_SCREEN = 800
HEIGHT_CONTROL_SCREEN = 200

# COLOR
BG_MAIN = "#34495e"
BG_GAME = "#050b14"
BG_GRAPH = "#2c3e50"
BG_STATS = "#dcdde1"
BG_CONTROL = "#dcdde1"

COLOR_PIPE_FILL = "#0d2a35"
COLOR_PIPE_OUTLINE = "#00f0ff"

COLOR_GROUND = "#111620"
COLOR_GROUND_BORDER = "#b829ea"

COLOR_LASER = "#ff007f"
COLOR_INFO_UI_GAME = "#78c4cb"

BG_LIGHT_BLUE = "#8DEEEE"

COLOR_DARK_GRAY = "#2F4F4F"
COLOR_LIGHT_GRAY = "#7f8c8d"
COLOR_WHITE = "#dcdde1"
COLOR_DARK_RED = "#DC143C"
COLOR_LIGHT_GREEN = "#1fd655"
COLOR_DARK_GREEN = "#7D952A"

# FRAME
FPS = 60
FRAME_TIME = int(1000 / FPS)

# BIRD SETTING
GRAVITY = 0.5
JUMP_STRENGTH = -8
BIRD_SIZE = 30

# PIPE SETTING
PIPE_SPEED = 4
PIPE_WIDTH = 60
PIPE_GAP = 150

# GROUND SETTING
GROUND_HEIGHT = 100


# GENETIC ALGORITHM SETTING

# POPULATION
POPULATION_SIZE = 100

#NEURAL NETWORK INPUT
INPUT_NODE = 4
HIDDEN_NODE = 5
OUTPUT_NODE = 1

# DATA OF CONTROL PANEL
MUTATION_RATE = 0.05

# NUMBER OF ELITE BIRDS
NUM_ELITISM = 5

# DIRECTORY PATHS
MODEL_PATH = "data/models"
EXPORT_PATH = "data/logs"

